<?php declare(strict_types=1);
namespace Frrame\Facade;
class AssetFacade{
	public static function index(string $index):string{
		return '<script>window.INDEX="'.$index.'";</script>'.PHP_EOL;
	}
	public static function viteEntry(string $entry):string{
		$viteEntry = 'resource/asset/script/'.$entry.'.js';
		if($_ENV['APP_PROD'] === '0'){
			$devUrl = 'http://localhost:5173';
			return <<<HTML
				<script type="module" src="{$devUrl}/@vite/client"></script>
				<script type="module" src="{$devUrl}/{$viteEntry}"></script>
			HTML;
		}
		$manifestPath = PUBLIC_PATH.'/dist/.vite/manifest.json';
		if(!file_exists($manifestPath)){
			return '';
		}
		$manifest = json_decode(file_get_contents($manifestPath), true);
		if(!isset($manifest[$viteEntry])){
			return '';
		}
		$file = $manifest[$viteEntry]['file'];
		$html = '<script type="module" src="'.HOME_URL.'/dist/'.$file.'"></script>'.PHP_EOL;
		// Append auto-extracted CSS files generated by Vite during build
		if(!empty($manifest[$viteEntry]['css'])){
			foreach($manifest[$viteEntry]['css'] as $cssFile){
				$html .= '<link rel="stylesheet" href="'.HOME_URL.'/dist/'.$cssFile.'">'.PHP_EOL;
			}
		}
		return $html;
	}
}